GET http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc
###
PATCH http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc

{
  "email": "yyj9694651@naver.com"
}
###
PATCH http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc

{
  "email": "yyj9694651@sookmyung.ac.kr",
  "role": "vi"
}
###
PATCH http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc

{
  "email": "yyj9694651@sookmyung.ac.kr",
  "role": "viewer"
}
###
PATCH http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc

{
  "email": "yyj9694651@sookmyung.ac.kr",
  "role": "editor"
}
###
GET http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc
###
PATCH http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/set-private
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc

{

}
###
GET http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc
###
PATCH http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc

{
  "email": "yyj9694651@sookmyung.ac.kr"
}
###
PATCH http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc

{
  "email": "yyj9694651@naver.com"
}
###
GET http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc
###
DELETE  http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users/679f83c2e1bf4cf300c0223e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc
###
GET http://localhost:3000/api/collections/67a20da731f9553465e2d8cb/sharing/shared-users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUxZTdjZDAwYzRhNTg0M2M4ODMwMyIsImVtYWlsIjoieXlqOTY5NDY1MUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2NzE0MjUsImV4cCI6MTczODY3NTAyNX0.l3Xx76ZgUZtavCFOEA4ghlE-uHBkiAqcgu4N-htIdrc
###



